export const INDUSTRIES = [
  "FinTech", "SaaS / Enterprise Software", "Consumer Health", "E-commerce",
  "Logistics & Supply Chain", "Manufacturing", "Climate Tech", "Telecom",
  "Real Estate", "Energy & Utilities", "EdTech", "Biotech",
  "Media", "Mobility", "FMCG"
];

export const STAGES = [
  { id: "pre-seed", label: "Pre-seed / Seed" },
  { id: "series-ab", label: "Series A–B" },
  { id: "scaleup", label: "Scaleup (C–D)" },
  { id: "pre-ipo", label: "Late stage / Pre-IPO" },
  { id: "public", label: "Public / IPO" },
  { id: "mnc", label: "Multinational" },
  { id: "pe-backed", label: "PE-backed" },
];

export const REGIONS = ["APAC", "EMEA", "Americas", "ANZ", "MENA"];

export const CANDIDATES = [
  {
    id: "c-014",
    code: "HLM-014",
    name: "Aiko Tanaka",
    avatar: 1,
    title: "Former CEO, Series D FinTech (Tokyo → Singapore)",
    location: "Singapore",
    region: "APAC",
    yearsAsCEO: 7,
    yearsLeadership: 14,
    industries: ["FinTech", "SaaS / Enterprise Software"],
    stages: ["series-ab", "scaleup", "pre-ipo"],
    summary: "Built and scaled a cross-border payments platform from Series A to a $1.4B exit. Strong technical product instinct paired with regulatory fluency across MAS, FSA, and OJK.",
    largestTeam: 480,
    largestRevenue: "$210M ARR",
    compMin: 900,
    compMax: 1400,
    compEq: "1.5%–3%",
    relocate: true,
    boards: 2,
    referredBy: "Operating Partner, Sequoia Capital",
    invitedOn: "2026-02-14",
    vettedOn: "2026-03-08",
    status: "Open to introductions",
    languages: ["English (Native)", "Japanese (Native)", "Mandarin (Conversational)"],
    education: [
      { school: "INSEAD", degree: "MBA", year: "2014" },
      { school: "University of Tokyo", degree: "BSc Computer Science", year: "2008" },
    ],
    experience: [
      { years: "2019 — 2025", role: "Co-founder & CEO", co: "Lattice Pay (acquired)", stage: "Scaleup → Exit", bullets: [
        "Raised $185M across Series A–D from Sequoia, Lightspeed, GIC.",
        "Scaled to 480 employees, $210M ARR, profitability achieved Q2 2024.",
        "Acquired by NYSE-listed payments group for $1.4B."
      ]},
      { years: "2016 — 2019", role: "VP Product", co: "Mercado Tech", stage: "Series C → Pre-IPO", bullets: [
        "Owned merchant-side payments roadmap across 9 markets.",
      ]},
      { years: "2014 — 2016", role: "Strategy Lead", co: "McKinsey & Company", stage: "—", bullets: [
        "FIG practice — Asia restructuring engagements.",
      ]},
    ],
    strengths: [
      { label: "Scaling 0 → 1", score: 95 },
      { label: "Capital markets", score: 88 },
      { label: "Regulatory navigation", score: 92 },
      { label: "Org design", score: 78 },
      { label: "Product instinct", score: 90 },
    ],
  },
  {
    id: "c-021",
    code: "HLM-021",
    name: "Marcus Whitfield",
    avatar: 2,
    title: "Former COO, Pre-IPO Enterprise SaaS",
    location: "London",
    region: "EMEA",
    yearsAsCEO: 4,
    yearsLeadership: 18,
    industries: ["SaaS / Enterprise Software"],
    stages: ["scaleup", "pre-ipo", "public"],
    summary: "Operator's operator. Took two enterprise SaaS businesses through the $50M → $500M ARR gauntlet. Known for ruthless GTM clarity and a deep bench of repeat CFOs and CROs.",
    largestTeam: 1900,
    largestRevenue: "$680M ARR",
    compMin: 1100,
    compMax: 1800,
    compEq: "0.8%–2%",
    relocate: true,
    boards: 3,
    referredBy: "Partner, Index Ventures",
    invitedOn: "2025-11-02",
    vettedOn: "2025-12-19",
    status: "Selectively considering",
    languages: ["English (Native)", "French (Professional)"],
    education: [
      { school: "London Business School", degree: "MBA", year: "2009" },
      { school: "Cambridge", degree: "MA Engineering", year: "2003" },
    ],
    experience: [
      { years: "2021 — 2025", role: "COO", co: "Stratiform", stage: "Pre-IPO", bullets: [
        "Scaled ARR from $180M to $680M; built EMEA + APAC GTM.",
      ]},
      { years: "2016 — 2021", role: "CEO", co: "Helio Systems", stage: "Series B → Series E", bullets: [
        "Founder-CEO. Sold to PE consortium for $720M.",
      ]},
    ],
    strengths: [
      { label: "GTM execution", score: 96 },
      { label: "Pricing & packaging", score: 91 },
      { label: "International expansion", score: 89 },
      { label: "Board operating", score: 87 },
      { label: "Capital markets", score: 84 },
    ],
  },
  {
    id: "c-007",
    code: "HLM-007",
    name: "Priya Raghavan",
    avatar: 3,
    title: "Group President, Consumer Health MNC",
    location: "Mumbai",
    region: "APAC",
    yearsAsCEO: 9,
    yearsLeadership: 22,
    industries: ["Consumer Health", "FMCG"],
    stages: ["mnc", "public"],
    summary: "P&L leader with full-stack MNC pedigree. Ran a $2.1B division across 14 markets, with a track record of rebuilding stagnant categories through brand and channel restructure.",
    largestTeam: 5400,
    largestRevenue: "$2.1B",
    compMin: 1400,
    compMax: 2200,
    compEq: "RSU-heavy",
    relocate: false,
    boards: 4,
    referredBy: "Chairman, Tata Consumer",
    invitedOn: "2025-09-08",
    vettedOn: "2025-10-04",
    status: "Open to introductions",
    languages: ["English (Native)", "Hindi (Native)", "Tamil (Native)"],
    education: [
      { school: "Wharton", degree: "MBA", year: "2003" },
      { school: "IIT Bombay", degree: "B.Tech", year: "1998" },
    ],
    experience: [
      { years: "2018 — 2025", role: "Group President, Consumer Health", co: "Aurora Wellness Plc", stage: "Public / MNC", bullets: [
        "$2.1B P&L; 14 markets; grew operating margin 720 bps.",
        "Led carve-out of pediatric nutrition business, $480M divestiture.",
      ]},
      { years: "2011 — 2018", role: "Managing Director, India & SEA", co: "Reckitt", stage: "MNC", bullets: [] },
    ],
    strengths: [
      { label: "P&L leadership", score: 98 },
      { label: "Brand portfolio", score: 92 },
      { label: "M&A integration", score: 88 },
      { label: "Multi-country ops", score: 95 },
      { label: "Board operating", score: 90 },
    ],
  },
  {
    id: "c-032",
    code: "HLM-032",
    name: "Daniel Okonkwo",
    avatar: 4,
    title: "Operating CEO, PE-backed Industrials",
    location: "Lagos",
    region: "EMEA",
    yearsAsCEO: 11,
    yearsLeadership: 21,
    industries: ["Manufacturing", "Logistics & Supply Chain"],
    stages: ["pe-backed", "mnc"],
    summary: "Turnaround specialist. Three PE-led transformations across industrial and logistics platforms — each delivered above-base case returns to sponsors within hold period.",
    largestTeam: 2200,
    largestRevenue: "$540M",
    compMin: 800,
    compMax: 1300,
    compEq: "Mgmt rollover",
    relocate: true,
    boards: 2,
    referredBy: "Managing Director, Helios Investment Partners",
    invitedOn: "2026-01-22",
    vettedOn: "2026-02-19",
    status: "Open to introductions",
    languages: ["English (Native)", "French (Professional)", "Yoruba (Native)"],
    education: [
      { school: "Harvard Business School", degree: "MBA", year: "2005" },
      { school: "University of Lagos", degree: "BEng Mechanical", year: "2000" },
    ],
    experience: [
      { years: "2020 — 2025", role: "CEO", co: "Sahel Industrial Group (Helios portfolio)", stage: "PE-backed", bullets: [
        "Consolidated 4 industrial assets, 2.6x MOIC at exit (2025).",
      ]},
      { years: "2016 — 2020", role: "CEO", co: "Northbound Logistics", stage: "PE-backed", bullets: [] },
    ],
    strengths: [
      { label: "Operational turnaround", score: 96 },
      { label: "M&A integration", score: 93 },
      { label: "Cost discipline", score: 95 },
      { label: "Working capital", score: 90 },
      { label: "Sponsor reporting", score: 92 },
    ],
  },
  {
    id: "c-018",
    code: "HLM-018",
    name: "Sofia Lindgren",
    avatar: 5,
    title: "Former CEO, Public E-commerce Group",
    location: "Stockholm",
    region: "EMEA",
    yearsAsCEO: 8,
    yearsLeadership: 19,
    industries: ["E-commerce", "FMCG"],
    stages: ["public", "scaleup"],
    summary: "Led Nordic e-commerce group through IPO and three years of public-market stewardship. Investor-day veteran. Strong instincts on category mix and last-mile economics.",
    largestTeam: 3100,
    largestRevenue: "$1.1B GMV",
    compMin: 1200,
    compMax: 1900,
    compEq: "RSU + perf",
    relocate: true,
    boards: 5,
    referredBy: "Board Chair, Norvik Capital",
    invitedOn: "2025-10-14",
    vettedOn: "2025-11-11",
    status: "Selectively considering",
    languages: ["English (Native)", "Swedish (Native)", "German (Professional)"],
    education: [
      { school: "Stockholm School of Economics", degree: "MSc Finance", year: "2006" },
    ],
    experience: [
      { years: "2017 — 2024", role: "CEO", co: "Halden Group", stage: "Public", bullets: [
        "IPO 2019, Nasdaq Stockholm. Market cap peak $2.4B.",
        "Returned to founder management buyout in 2024.",
      ]},
    ],
    strengths: [
      { label: "Public-market communication", score: 94 },
      { label: "Marketplace economics", score: 91 },
      { label: "Brand & category", score: 89 },
      { label: "Board operating", score: 92 },
    ],
  },
  {
    id: "c-040",
    code: "HLM-040",
    name: "Henrik Westergaard",
    avatar: 6,
    title: "CEO, Series C Cross-border Logistics",
    location: "Copenhagen",
    region: "EMEA",
    yearsAsCEO: 5,
    yearsLeadership: 16,
    industries: ["Logistics & Supply Chain", "Mobility"],
    stages: ["scaleup"],
    summary: "Built a B2B freight platform serving 1,800 mid-market exporters. Active operator — won't take a board seat without permission to run the room.",
    largestTeam: 620,
    largestRevenue: "$310M GMV",
    compMin: 850,
    compMax: 1300,
    compEq: "2%–4%",
    relocate: true,
    boards: 1,
    referredBy: "Partner, Atomico",
    invitedOn: "2026-03-02",
    vettedOn: "2026-04-04",
    status: "Open to introductions",
    languages: ["English (Native)", "Danish (Native)", "German (Native)"],
    education: [
      { school: "CBS Copenhagen", degree: "MSc Logistics", year: "2010" },
    ],
    experience: [
      { years: "2020 — 2025", role: "Co-founder & CEO", co: "Frakthus", stage: "Series A → C", bullets: [
        "Raised $94M; profitable at the unit level by month 28.",
      ]},
    ],
    strengths: [
      { label: "Scaling 0 → 1", score: 92 },
      { label: "Operational rigor", score: 94 },
      { label: "Fundraising", score: 87 },
      { label: "Sales-led GTM", score: 86 },
    ],
  },
  {
    id: "c-027",
    code: "HLM-027",
    name: "Mei-Lin Chen",
    avatar: 1,
    title: "CEO, Climate Tech (Series B)",
    location: "Singapore",
    region: "APAC",
    yearsAsCEO: 3,
    yearsLeadership: 12,
    industries: ["Climate Tech", "Energy & Utilities"],
    stages: ["series-ab"],
    summary: "Energy systems engineer turned founder. Building industrial carbon capture for cement and steel. Deep technical credibility paired with first-class capital-raising instincts.",
    largestTeam: 110,
    largestRevenue: "$24M ARR",
    compMin: 600,
    compMax: 900,
    compEq: "3%–6%",
    relocate: true,
    boards: 0,
    referredBy: "Partner, Breakthrough Energy Ventures",
    invitedOn: "2026-04-11",
    vettedOn: "2026-05-02",
    status: "Open to introductions",
    languages: ["English (Native)", "Mandarin (Native)"],
    education: [
      { school: "Stanford", degree: "PhD Energy Systems", year: "2017" },
      { school: "Tsinghua University", degree: "BEng Mechanical", year: "2012" },
    ],
    experience: [
      { years: "2022 — 2025", role: "Co-founder & CEO", co: "Andesite Carbon", stage: "Series A → B", bullets: [
        "Raised $76M from BEV, Lowercarbon, Temasek.",
      ]},
      { years: "2017 — 2022", role: "Research Lead", co: "Shell New Energies", stage: "MNC R&D", bullets: [] },
    ],
    strengths: [
      { label: "Deep-tech R&D", score: 96 },
      { label: "Capital raising", score: 88 },
      { label: "Technical recruiting", score: 90 },
      { label: "Govt & policy", score: 85 },
    ],
  },
  {
    id: "c-051",
    code: "HLM-051",
    name: "Tomás Vega",
    avatar: 2,
    title: "President, Telecom (Latin America)",
    location: "Mexico City",
    region: "Americas",
    yearsAsCEO: 12,
    yearsLeadership: 26,
    industries: ["Telecom"],
    stages: ["mnc", "public"],
    summary: "30-year telecom veteran. Built mobile and fiber operations across six Latin American markets. Deep regulatory networks. Currently chairing two boards.",
    largestTeam: 18000,
    largestRevenue: "$4.8B",
    compMin: 1800,
    compMax: 2800,
    compEq: "RSU + perf",
    relocate: false,
    boards: 3,
    referredBy: "Lead Director, América Móvil",
    invitedOn: "2025-07-19",
    vettedOn: "2025-08-22",
    status: "Board-only",
    languages: ["English (Native)", "Spanish (Native)", "Portuguese (Professional)"],
    education: [
      { school: "MIT Sloan", degree: "MBA", year: "1998" },
      { school: "ITESM", degree: "BEng Electrical", year: "1992" },
    ],
    experience: [
      { years: "2014 — 2024", role: "President, Latin America", co: "Telmark Global", stage: "Public / MNC", bullets: [] },
    ],
    strengths: [
      { label: "Regulatory navigation", score: 97 },
      { label: "Large-scale ops", score: 95 },
      { label: "M&A integration", score: 93 },
    ],
  },
  {
    id: "c-035",
    code: "HLM-035",
    name: "Anita Borisov",
    avatar: 3,
    title: "CEO, Pre-IPO Proptech",
    location: "Berlin",
    region: "EMEA",
    yearsAsCEO: 6,
    yearsLeadership: 17,
    industries: ["Real Estate", "FinTech"],
    stages: ["pre-ipo"],
    summary: "Bridged the gap between legacy real estate and software. Took a commercial proptech platform from $40M ARR to filed S-1 in 38 months.",
    largestTeam: 740,
    largestRevenue: "$280M ARR",
    compMin: 1000,
    compMax: 1500,
    compEq: "1.2%–2.4%",
    relocate: true,
    boards: 1,
    referredBy: "Partner, General Atlantic",
    invitedOn: "2025-12-05",
    vettedOn: "2026-01-18",
    status: "Open to introductions",
    languages: ["English (Native)", "German (Native)", "Russian (Native)"],
    education: [
      { school: "Bocconi", degree: "MBA", year: "2010" },
    ],
    experience: [
      { years: "2019 — 2025", role: "Co-founder & CEO", co: "Domena", stage: "Series B → Pre-IPO", bullets: [
        "Filed S-1 January 2025; expected listing H2.",
      ]},
    ],
    strengths: [
      { label: "Capital markets", score: 94 },
      { label: "Vertical SaaS GTM", score: 91 },
      { label: "Strategic finance", score: 89 },
    ],
  },
  {
    id: "c-046",
    code: "HLM-046",
    name: "James Carmichael",
    avatar: 4,
    title: "Former CEO, Public Utility Group",
    location: "Sydney",
    region: "ANZ",
    yearsAsCEO: 10,
    yearsLeadership: 24,
    industries: ["Energy & Utilities"],
    stages: ["public"],
    summary: "Steady hand on a $6B public utility through energy transition. Plain-spoken with regulators, calm with investors, beloved by line managers.",
    largestTeam: 8600,
    largestRevenue: "$6.1B",
    compMin: 1600,
    compMax: 2400,
    compEq: "RSU + perf",
    relocate: false,
    boards: 4,
    referredBy: "Chairman, Origin Energy",
    invitedOn: "2025-08-30",
    vettedOn: "2025-10-01",
    status: "Board-only",
    languages: ["English (Native)"],
    education: [
      { school: "AGSM", degree: "MBA", year: "2001" },
      { school: "University of Melbourne", degree: "BEng Civil", year: "1996" },
    ],
    experience: [
      { years: "2014 — 2024", role: "CEO", co: "Endeavour Power", stage: "Public", bullets: [] },
    ],
    strengths: [
      { label: "Regulatory navigation", score: 96 },
      { label: "Capital allocation", score: 93 },
      { label: "Crisis leadership", score: 95 },
    ],
  },
  {
    id: "c-058",
    code: "HLM-058",
    name: "Yara Haddad",
    avatar: 5,
    title: "CEO, Series C EdTech",
    location: "Dubai",
    region: "MENA",
    yearsAsCEO: 4,
    yearsLeadership: 13,
    industries: ["EdTech", "Consumer Health"],
    stages: ["series-ab", "scaleup"],
    summary: "Founder of MENA's leading B2B learning platform. Quietly built a 1,400-employee operation across 7 markets while keeping burn well below benchmark.",
    largestTeam: 1400,
    largestRevenue: "$96M ARR",
    compMin: 700,
    compMax: 1100,
    compEq: "2%–4%",
    relocate: true,
    boards: 1,
    referredBy: "Partner, Wamda Capital",
    invitedOn: "2026-02-04",
    vettedOn: "2026-03-12",
    status: "Open to introductions",
    languages: ["English (Native)", "Arabic (Native)", "French (Professional)"],
    education: [
      { school: "INSEAD", degree: "MBA", year: "2013" },
    ],
    experience: [
      { years: "2020 — 2025", role: "Co-founder & CEO", co: "Manarah Learning", stage: "Series A → C", bullets: [] },
    ],
    strengths: [
      { label: "Capital efficiency", score: 95 },
      { label: "Multi-country ops", score: 89 },
      { label: "Product-led growth", score: 86 },
    ],
  },
  {
    id: "c-063",
    code: "HLM-063",
    name: "Rohan Mehta",
    avatar: 6,
    title: "CEO, Series B Biotech",
    location: "Boston",
    region: "Americas",
    yearsAsCEO: 5,
    yearsLeadership: 17,
    industries: ["Biotech", "Consumer Health"],
    stages: ["series-ab"],
    summary: "MD-PhD turned biotech operator. Built a precision-oncology platform with three clinical-stage assets and a strategic option to either spin out or go public.",
    largestTeam: 240,
    largestRevenue: "Pre-revenue",
    compMin: 800,
    compMax: 1200,
    compEq: "4%–7%",
    relocate: true,
    boards: 2,
    referredBy: "Partner, Flagship Pioneering",
    invitedOn: "2026-01-09",
    vettedOn: "2026-02-15",
    status: "Open to introductions",
    languages: ["English (Native)", "Hindi (Native)"],
    education: [
      { school: "Harvard Medical School", degree: "MD–PhD", year: "2010" },
    ],
    experience: [
      { years: "2020 — 2025", role: "Co-founder & CEO", co: "Lattix Oncology", stage: "Series A → B", bullets: [] },
    ],
    strengths: [
      { label: "Scientific judgement", score: 97 },
      { label: "Capital raising", score: 88 },
      { label: "Clinical strategy", score: 94 },
    ],
  },
];

export const MANDATES = [
  {
    id: "m-201",
    code: "MND-201",
    title: "CEO — Series D Mobility Platform",
    client: "Confidential (Tier 1 fund-backed)",
    location: "Singapore / APAC",
    industries: ["Mobility", "Logistics & Supply Chain"],
    stage: "Scaleup (C–D)",
    compRange: "$1.4M – $1.9M + 1.5–2.5% equity",
    shortlist: 9,
    introduced: 4,
    finalists: 2,
    progress: 64,
    openedOn: "2026-03-04",
    nda: true,
    status: "Active",
    daysOpen: 81,
  },
  {
    id: "m-198",
    code: "MND-198",
    title: "CEO — APAC Cloud Infrastructure",
    client: "Pan-Asian Strategic, NDA in place",
    location: "Tokyo or Singapore",
    industries: ["SaaS / Enterprise Software"],
    stage: "Pre-IPO",
    compRange: "$1.6M – $2.2M + RSU package",
    shortlist: 14,
    introduced: 6,
    finalists: 3,
    progress: 80,
    openedOn: "2026-01-19",
    nda: true,
    status: "Active — final stage",
    daysOpen: 125,
  },
  {
    id: "m-187",
    code: "MND-187",
    title: "Group CEO — Regional Healthcare Network",
    client: "PE-led roll-up, sponsor: confidential",
    location: "Mumbai / Pan-India",
    industries: ["Consumer Health"],
    stage: "PE-backed",
    compRange: "$1.1M base + mgmt rollover",
    shortlist: 7,
    introduced: 3,
    finalists: 1,
    progress: 48,
    openedOn: "2026-02-21",
    nda: true,
    status: "Active",
    daysOpen: 92,
  },
  {
    id: "m-176",
    code: "MND-176",
    title: "CEO — Industrial AI (Stealth)",
    client: "Founder-led, $80M Series B closing",
    location: "San Francisco / Hybrid",
    industries: ["SaaS / Enterprise Software", "Manufacturing"],
    stage: "Series A–B",
    compRange: "$650k – $900k + 3–5% equity",
    shortlist: 6,
    introduced: 2,
    finalists: 0,
    progress: 28,
    openedOn: "2026-04-12",
    nda: true,
    status: "Active — early stage",
    daysOpen: 42,
  },
];

export const ACTIVITY = [
  { kind: "intro", actor: "You", text: "introduced Aiko Tanaka (HLM-014) to MND-201", time: "12m ago", dot: "accent" },
  { kind: "vetted", actor: "Helm Research", text: "completed vetting on Mei-Lin Chen (HLM-027)", time: "2h ago", dot: "positive" },
  { kind: "reply", actor: "Marcus Whitfield", text: "responded — Open to a 30-min call next week", time: "5h ago", dot: "accent" },
  { kind: "invite", actor: "Partner referral", text: "1 candidate invited via your link this week", time: "Yesterday", dot: "" },
  { kind: "shortlist", actor: "You", text: "added Sofia Lindgren to MND-198 shortlist", time: "2d ago", dot: "" },
  { kind: "decline", actor: "Tomás Vega", text: "passed on MND-187 — board commitments through 2026", time: "3d ago", dot: "" },
];
